### ISSUE TITLE
Review data models and the use of email field

### ISSUE THREAD

**Issue by jayesh92** [anitab-org/vms#105]
Volunteer model has a one-to-one relationship with User model, which already has an email field. We also have an email field explicitly in Volunteer model. 
~~As per my previous tests, we are using email field of User model to check replication and login/logout. However, in profile tab of Volunteer views we have a field to display email, which is fetching from email field of Volunteer model. Why are having redundancy in email here ?~~
**EDIT**
Why do we need email field explicitly, why not use `user.email` ?

@Nerdylicious @willingc @vubo

**Comment by willingc** [comment]
@jayesh92 Would it be possible to point out specific files and lines of code to clarify your comments? Thanks!

**Comment by willingc** [comment]
@vubo @jayesh92 @tapasweni-pathak @Nerdylicious @rosariorobinson Since we are getting pretty far along in the GSOC timeline, I wanted to take a moment to share a few open source references and an article on github issues. As we work toward our individual milestones and goals, detailed, effective communication becomes super important. It's important for getting our work done, but it's even more important for maintaining the project and handing off the projects to the next group of contributors (though I hope everyone will continue to contribute as they are able).

* http://www.ianbicking.org/blog/2014/03/use-github-issues-to-organize-a-project.html
* http://artofcommunityonline.org/Art_of_Community_Second_Edition.pdf
* http://producingoss.com/

Thanks to everyone for your professional and hard work on these projects. It's been key to good workflow and productivity. I'm pleased with the progress that is being made on vms and other projects, and I'm challenging everyone to ask themselves three questions when leaving comments:

- [ ]  Is it detailed and specific?
- [ ]  Would someone who doesn't look at the code everyday (such as another mentor or future contributor) understand what to look at?
- [ ]  Is it clear what the next step would be?

@jayesh92 :+1:  on raising the question about the data models and email attribute. I'm looking forward to more detail :smiley:

**Comment by jayesh92** [comment]
@willingc Thanks for your suggestions !
https://github.com/systers/vms/blob/develop/vms/volunteer/models.py#L81 and https://github.com/systers/vms/blob/develop/vms/volunteer/models.py#L118
- As you can see in the links stated above, volunteer model contains an email field and a one-to-one relationship with user.
- Why do we explicitly need an email field, when we can already get it using `volunteer.user.email`
- As I had pointed out in some earlier issue, we are using `user.username` a unique identifier and not `user.email`
- Profile view: https://github.com/systers/vms/blob/develop/vms/volunteer/views.py#L100 and Profile Template: https://github.com/systers/vms/blob/develop/vms/volunteer/templates/volunteer/profile.html#L35 , it uses email defined in volunteer model and not `volunteer.user.email`
- While registering also, https://github.com/systers/vms/blob/develop/vms/volunteer/templates/volunteer/profile.html#L35 we are only using username & password  fields of pre-defined user model.
- Yes, there is a consistency that we are following email of volunteer model across the app ( I had wrongly interpreted it earlier ), But why not use of user itself ?

**Comment by willingc** [comment]
@jayesh92 Thank you!!! This helps a bunch. Is there a repo link to the automated tests that you have been working on? It would be helpful for me to do a quick scan of the tests.

@vubo, @tapasweni-pathak, @Nerdylicious - Please share your thoughts. I will need to take some time to look at the data model definition doc as well as Django 1.8 docs and the current code base to form an opinion on the approach.

**Comment by vubo** [comment]
@willingc thank you very much for the useful links!

Since the code is programmed by @Nerdylicious, Irish can explain, why she created email field explicitly. Perhaps it was necessary.

But in general I agree with @jayesh92, we should use ```user.email``` since Django provides this field.

**Comment by Nerdylicious** [comment]
@willingc @vubo

I included the email field (and also the first_name and last_name fields) in the Volunteer model because there might be a chance that we would use a different module for authentication that may not include first_name, last_name and email fields, so I included them in the Volunteer table (and also the Admin table). If we were to replace the django auth tables with something else then the auth_user table would be dropped and we would lose information like first_name, last_name and email.

When I wrote the code I ignored the first_name, last_name and email field in the auth_user table and used the corresponding fields in the Volunteer table.

The database was designed so that it could stand on its own from the automatically generated django tables such as auth_user.

The downside is that people get confused as to which email fields to use and why it is duplicated.

**Comment by willingc** [comment]
@Nerdylicious Thank you for the detailed message. I appreciate it and it adds context for me :sunflower: 

@vubo I'm going to do a little thinking on this.

**Comment by tapasweni-pathak** [comment]
@willingc  I need some time, before giving my suggestion on this.

**Comment by jayesh92** [comment]
+1 on Irish's views. We should probably go by fields in volunteer fields itself

**Comment by abha224** [comment]
Closing this issue because it has been inactive for a few years.
